### PR TITLE
fix(extensions/kind): use correct types in download.ts

### PR DESCRIPTION
**Pull request by Blaimi**
The typehints in the download-script for projectcontour introduced with 35d7c77bd484e9ebdba74395455bb66ea83dba7e are not working (anymore?). This PR fixes them.

### CODE REVIEW

**Comment by benoitf** [comment]
hello @Blaimi , how to you see the current error ?

```
pnpm -C extensions/kind install:contour

> kind@1.18.0-next install:contour extensions/kind
> tsx ./scripts/download.ts

Downloading Contour manifests from https://github.com/projectcontour/contour/examples/render/contour.yaml version v1.30.2
Contour.yaml available at extensions/kind/src/resources/contour.yaml
```

**Comment by Blaimi** [comment]
Webstorm is "screaming" ;-)

grafik

And as far as my dilletantic TypeScript-skills don't lead me wrong, Webstorm is right. The type `ReposGetContentResponseData` seems not to be exported by `'@octokit/core/dist-types/types'`. The typehints on `manifests` (defined in [Line 54](https://github.com/podman-desktop/podman-desktop/pull/11733/files#diff-f540c220f79f1c8e1be3c7a381cd6465c8e29e31cfcb46b63b44bd18a4fb1a8cR54)) are also not working.

**Comment by benoitf** [comment]
` ./node_modules/.bin/tsc --noEmit extensions/kind/scripts/download.ts --skipLibCheck`

**Comment by benoitf** [comment]
```
extensions/kind/scripts/download.ts:23:31 - error TS2305: Module '"@octokit/core/dist-types/types"' has no exported member 'ReposGetContentResponseData'.

23 import type { OctokitOptions, ReposGetContentResponseData, OctokitResponse } from '@octokit/core/dist-types/types';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~

extensions/kind/scripts/download.ts:23:60 - error TS2305: Module '"@octokit/core/dist-types/types"' has no exported member 'OctokitResponse'.

23 import type { OctokitOptions, ReposGetContentResponseData, OctokitResponse } from '@octokit/core/dist-types/types';
                                                              ~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: extensions/kind/scripts/download.ts:23
```


cc @gastoner

**Comment by Blaimi** [comment]
Found it: `tsx` doesn't do any type-check ([docs](https://tsx.is/typescript#development-workflow)). Running tsc on the file before:
```~/workspace/podman-desktop/podman-desktop/extensions/kind git:[main]
tsx ./scripts/download.ts
Downloading Contour manifests from https://github.com/projectcontour/contour/examples/render/contour.yaml version v1.30.1
Contour.yaml available at /home/user/workspace/podman-desktop/podman-desktop/extensions/kind/src/resources/contour.yaml
~/workspace/podman-desktop/podman-desktop/extensions/kind git:[main]
tsc --noEmit ./scripts/download.ts
scripts/download.ts:23:31 - error TS2305: Module '"@octokit/core/dist-types/types"' has no exported member 'ReposGetContentResponseData'.

23 import type { OctokitOptions, ReposGetContentResponseData, OctokitResponse } from '@octokit/core/dist-types/types';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~

scripts/download.ts:23:60 - error TS2305: Module '"@octokit/core/dist-types/types"' has no exported member 'OctokitResponse'.

23 import type { OctokitOptions, ReposGetContentResponseData, OctokitResponse } from '@octokit/core/dist-types/types';
                                                              ~~~~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:26:42 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

26         cb?: (response: ServerResponse | ResponseLike) => void
                                            ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:77:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

77             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:81:69 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

81         on(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                       ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:84:71 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

84         once(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                         ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:89:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

89             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:95:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

95             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:104:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

104             listener: (response: ServerResponse | ResponseLike) => void
                                                      ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:108:70 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

108         off(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                         ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:112:73 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

112         listeners(event: 'response'): Array<(response: ServerResponse | ResponseLike) => void>;
                                                                            ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:115:76 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

115         rawListeners(event: 'response'): Array<(response: ServerResponse | ResponseLike) => void>;
                                                                               ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:118:60 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

118         emit(event: 'response', response: ServerResponse | ResponseLike): boolean;
                                                               ~~~~~~~~~~~~


Found 13 errors in 2 files.

Errors  Files
     2  scripts/download.ts:23
    11  ../../node_modules/@types/cacheable-request/index.d.ts:26
```

and after:

```
~/workspace/podman-desktop/podman-desktop/extensions/kind git:[fix/kind-download-types]
tsc --noEmit ./scripts/download.ts
../../node_modules/@types/cacheable-request/index.d.ts:26:42 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

26         cb?: (response: ServerResponse | ResponseLike) => void
                                            ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:77:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

77             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:81:69 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

81         on(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                       ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:84:71 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

84         once(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                         ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:89:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

89             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:95:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

95             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:104:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

104             listener: (response: ServerResponse | ResponseLike) => void
                                                      ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:108:70 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

108         off(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                         ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:112:73 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

112         listeners(event: 'response'): Array<(response: ServerResponse | ResponseLike) => void>;
                                                                            ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:115:76 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

115         rawListeners(event: 'response'): Array<(response: ServerResponse | ResponseLike) => void>;
                                                                               ~~~~~~~~~~~~

../../node_modules/@types/cacheable-request/index.d.ts:118:60 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

118         emit(event: 'response', response: ServerResponse | ResponseLike): boolean;
                                                               ~~~~~~~~~~~~


Found 11 errors in the same file, starting at: ../../node_modules/@types/cacheable-request/index.d.ts:26
```

**Review by benoitf — APPROVED** [review]
thanks @Blaimi 

as a follow-up I'll create an issue to ensure scripts are part of the `pnpm typecheck` check

**Review by gastoner — APPROVED** [review]
LGTM, I think the VSCode have added those imports
